In [1]:
# def fun1(x1,x2,x3):   
#   return round(x1**2+x2**2+x3**2)
def crossover1(m1,m2):  
  a =np.random.randint(0, high=2, size=(2, 1))
    #change the repeated value  # ? if two list's repeated value different? how to do?
    #set same len(repeated value) 
  
  m1[a[0]],m2[a[1]] = m2[a[1]],m1[a[0]]
  return m1,m2
def mutation(m):
 # random change the position
  a = np.random.randint(0,3)
  b = np.random.randint(0,3)
  while a == b:
    a = np.random.randint(0,3)
    b = np.random.randint(0,3)
    if a != b: 
      break
  m[a],m[b] = m[b],m[a]
  return m

def fun(m): # equation 
  return m[0]**2+m[1]**2+m[2]**2


In [5]:
import random
import numpy as np
np.random.seed(10) #fixed seeds
m=np.random.randint(1, high=4, size=(5, 3)) #generate 5*3 matrix
#m = np.random.rand(5,3)
print(m)
n=0
while n<10:
  #crossover
  for i in range(0,4):
     
    m1=m[i]
    m2=m[i+1]
    print(m1)
    
    print(m2)
    crossover1(m1,m2)
  
  #mutation 
  A=0
  B=1#小数的范围A ~ B
  a=random.uniform(A,B)
  C=1#随机数的精度round(数值，精度)
  mutation_prob = round(a,C)
  #p is chosen to be the mutation point index
  p =np.random.randint(0, high=4)
  if mutation_prob == 0.1:
      mutation(m[p])
  # delete the worst 2 gene
  list = []
  for j in range(5):
    list.append(fun(m[j]))  #get all the final value of m[0],m[1],..m[5]
  idx_worst = []
  for k in range(5):
    if fun(m[k]) == max(list):
      idx_worst.append(k)
  for l in range(len(idx_worst)):
    m[idx_worst[l]] = np.random.randint(1, high=4, size=(1, 3))
  n+=1
ans = []
for i in range(5):
  ans.append(fun(m[i]))
#  print(fun(m[i]))
print(min(ans))





[[2 2 1]
 [1 2 1]
 [2 2 1]
 [2 2 3]
 [1 2 1]]
[2 2 1]
[1 2 1]
[2 2 1]
[2 2 1]
[2 2 1]
[2 2 3]
[2 2 3]
[1 2 1]
[1 2 1]
[2 2 1]
[2 1 1]
[2 2 1]
[2 2 1]
[3 1 3]
[3 2 3]
[1 2 1]
[2 2 1]
[2 1 1]
[2 2 1]
[1 2 1]
[2 2 1]
[2 2 2]
[2 2 2]
[2 2 1]
[1 2 1]
[1 2 1]
[1 2 1]
[2 2 1]
[2 1 1]
[2 1 3]
[2 1 3]
[2 2 1]
[1 2 1]
[2 2 1]
[1 2 1]
[2 1 1]
[2 1 1]
[1 2 3]
[1 1 3]
[1 2 1]
[2 2 1]
[1 2 1]
[2 2 1]
[2 2 1]
[2 2 1]
[1 3 1]
[2 3 1]
[1 1 1]
[1 2 1]
[2 2 1]
[2 2 1]
[2 1 1]
[2 2 1]
[3 3 1]
[2 3 1]
[2 1 1]
[1 2 1]
[1 2 1]
[1 2 1]
[3 1 1]
[1 1 1]
[1 3 1]
[1 1 1]
[2 2 1]
[1 2 1]
[3 2 2]
[3 2 2]
[1 3 1]
[1 3 1]
[1 2 1]
[1 1 1]
[1 2 1]
[1 2 1]
[3 2 1]
[1 2 1]
[2 3 1]
[1 3 1]
[1 2 1]
[1 3 1]
[1 1 1]
3


In [6]:

def crossover1(m1,m2):  
  a =np.random.randint(0, high=2, size=(2, 1))
    #change the repeated value  # ? if two list's repeated value different? how to do?
    #set same len(repeated value) 
  
  m1[a[0]],m2[a[1]] = m2[a[1]],m1[a[0]]
  return m1,m2
def mutation(m):
 # random change the position
  a = np.random.randint(0,3)
  b = np.random.randint(0,3)
  while a == b:
    a = np.random.randint(0,3)
    b = np.random.randint(0,3)
    if a != b: 
      break
  m[a],m[b] = m[b],m[a]
  return m

def residual(x,y,b): # equation 
  return (y-(b[0]+b[1]*x[1]+b[2]*x[2])**2)**0.5


In [7]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.data[2])
print(iris.target[0])


[4.7 3.2 1.3 0.2]
0


In [8]:
import random
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
x = iris.data
y = iris.target
np.random.seed(10) #fixed seeds
b=np.random.randint(1, high=4, size=(5, 3)) #generate 5*3 matrix

print(b)
n=0
while n<10:
  #crossover
  for i in range(0,4):
    
    m1=m[i]
    m2=m[i+1]
    print(m1)
    
    print(m2)
    crossover1(m1,m2)
  
  #mutation 
  A=0
  B=1#小数的范围A ~ B
  a=random.uniform(A,B)
  C=1#随机数的精度round(数值，精度)
  mutation_prob = round(a,C)
  #p is chosen to be the mutation point index
  p =np.random.randint(0, high=4)
  if mutation_prob == 0.1:
      mutation(m[p])
  # delete the worst 2 gene
  list = []
  for j in range(5):
    list.append(fun(m[j]))  #get all the final value of m[0],m[1],..m[5]
  idx_worst = []
  for k in range(5):
    if fun(m[k]) == max(list):
      idx_worst.append(k)
  for l in range(len(idx_worst)):
    m[idx_worst[l]] = np.random.randint(1, high=4, size=(1, 3))
  n+=1
ans = []
for i in range(5):
  ans.append(fun(m[i]))
#  print(fun(m[i]))
print(min(ans))




[[2 2 1]
 [1 2 1]
 [2 2 1]
 [2 2 3]
 [1 2 1]]
[2 2 3]
[2 2 1]
[2 2 1]
[1 2 1]
[2 2 1]
[1 1 1]
[2 1 1]
[1 3 1]
[3 1 3]
[1 2 1]
[1 3 1]
[2 1 1]
[1 1 1]
[3 1 1]
[3 1 1]
[1 2 1]
[2 1 3]
[3 3 2]
[3 2 2]
[1 1 1]
[1 2 1]
[3 1 1]
[3 1 1]
[1 2 1]
[3 3 1]
[3 1 2]
[3 1 2]
[1 2 1]
[3 2 1]
[2 1 1]
[2 2 1]
[1 3 1]
[1 2 3]
[1 1 2]
[1 2 2]
[3 1 1]
[3 1 1]
[1 2 1]
[3 2 1]
[2 3 1]
[1 1 3]
[1 2 2]
[1 2 2]
[1 1 1]
[1 1 1]
[2 2 1]
[1 2 1]
[2 1 1]
[2 3 3]
[1 2 2]
[3 2 2]
[2 1 1]
[2 3 1]
[1 1 1]
[2 1 1]
[2 2 1]
[3 2 2]
[1 2 2]
[2 2 2]
[1 3 1]
[2 3 1]
[2 1 1]
[2 3 1]
[2 2 1]
[2 1 2]
[1 2 2]
[1 2 2]
[2 1 1]
[2 2 1]
[2 2 1]
[2 2 1]
[2 2 1]
[2 3 2]
[1 1 2]
[3 1 2]
[2 3 1]
[3 3 1]
[3 2 1]
[3 3 1]
[2 2 1]
3


In [10]:
#mutation 
import random
A=0
B=1#小数的范围A ~ B
a=random.uniform(A,B)
C=1#随机数的精度round(数值，精度)
mutation_prob = round(a,C)
if mutation_prob == 0.1:
    mutation(m)


